/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPublicAdminMcpTokenRouteImport } from './routes/api/public/admin-mcp-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminMcpTokenRoute = ApiPublicAdminMcpTokenRouteImport.update({
  id: '/api/public/admin-mcp-token',
  path: '/api/public/admin-mcp-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/admin-mcp-token': typeof ApiPublicAdminMcpTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/admin-mcp-token': typeof ApiPublicAdminMcpTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/admin-mcp-token': typeof ApiPublicAdminMcpTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mcp' | '/api/public/admin-mcp-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mcp' | '/api/public/admin-mcp-token'
  id: '__root__' | '/' | '/api/mcp' | '/api/public/admin-mcp-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPublicAdminMcpTokenRoute: typeof ApiPublicAdminMcpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-mcp-token': {
      id: '/api/public/admin-mcp-token'
      path: '/api/public/admin-mcp-token'
      fullPath: '/api/public/admin-mcp-token'
      preLoaderRoute: typeof ApiPublicAdminMcpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPublicAdminMcpTokenRoute: ApiPublicAdminMcpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
